basePath: /api/v1
definitions:
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  aws.TmpTokenStruct:
    properties:
      access_key_id:
        type: string
      expiration:
        type: integer
      secret_access_key:
        type: string
      session_token:
        type: string
    type: object
  models.ArticleDto:
    properties:
      author_id:
        type: integer
      author_name:
        type: string
      category_id:
        type: integer
      category_name:
        type: string
      content:
        type: string
      cover_image_url:
        type: string
      created_at:
        type: integer
      created_by:
        type: string
      id:
        type: integer
      language:
        type: string
      meta_desc:
        type: string
      page_title:
        type: string
      related_articles:
        type: string
      seo_title:
        type: string
      seo_url:
        type: string
      state:
        type: integer
      updated_at:
        type: integer
      updated_by:
        type: string
    type: object
  models.AuthorDto:
    properties:
      age:
        type: integer
      created_at:
        type: integer
      created_by:
        type: string
      desc:
        type: string
      gender:
        type: integer
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: integer
      updated_by:
        type: string
    type: object
  models.CategoryDto:
    properties:
      created_at:
        type: integer
      created_by:
        type: string
      id:
        type: integer
      name:
        type: string
      state:
        type: integer
      updated_at:
        type: integer
      updated_by:
        type: string
    type: object
  models.LotteryDto:
    properties:
      content:
        type: string
      keyword:
        type: string
      score:
        type: integer
    type: object
  models.LuckyTodayDto:
    properties:
      song:
        type: string
      spell:
        type: string
      todo:
        type: string
    type: object
  models.UserDto:
    properties:
      created_at:
        type: integer
      created_by:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: integer
      updated_by:
        type: string
    type: object
  v1.AddArticleForm:
    properties:
      author_id:
        type: integer
      category_id:
        type: integer
      content:
        type: string
      cover_image_url:
        type: string
      language:
        default: jp
        enum:
        - jp
        - zh
        - en
        type: string
      meta_desc:
        type: string
      page_title:
        type: string
      related_articles:
        type: string
      seo_title:
        type: string
      seo_url:
        type: string
      state:
        default: 1
        description: 0表示禁用，1表示启用
        enum:
        - 1
        - 0
        type: integer
    required:
    - author_id
    - category_id
    - content
    - cover_image_url
    - language
    - meta_desc
    - page_title
    - related_articles
    - seo_title
    - seo_url
    - state
    type: object
  v1.AddAuthorForm:
    properties:
      age:
        type: integer
      desc:
        type: string
      gender:
        default: 2
        description: 1表示男，2表示女
        enum:
        - 1
        - 2
        type: integer
      name:
        type: string
    required:
    - age
    - desc
    - gender
    - name
    type: object
  v1.AddCategoryForm:
    properties:
      name:
        type: string
      state:
        default: 1
        type: integer
    required:
    - name
    - state
    type: object
  v1.GetArticlesResponse:
    properties:
      count:
        type: integer
      lists:
        items:
          $ref: '#/definitions/models.ArticleDto'
        type: array
    type: object
  v1.GetAuthorsResponse:
    properties:
      count:
        type: integer
      lists:
        items:
          $ref: '#/definitions/models.AuthorDto'
        type: array
    type: object
  v1.GetCategoryResponse:
    properties:
      count:
        type: integer
      lists:
        items:
          $ref: '#/definitions/models.CategoryDto'
        type: array
    type: object
  v1.GetLotteryResponse:
    properties:
      lotteryContent:
        $ref: '#/definitions/models.LotteryDto'
      luckyContent:
        $ref: '#/definitions/models.LuckyTodayDto'
    type: object
  v1.GetUserResponse:
    properties:
      count:
        type: integer
      lists:
        items:
          $ref: '#/definitions/models.UserDto'
        type: array
    type: object
  v1.auth:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact:
    email: cwater4t@gmail.com
    name: cw4t
  description: 小宇宙项目用户交互API、管理后台API
  title: 小小の宇宙API文档
  version: "1.0"
paths:
  /manager/articles:
    get:
      parameters:
      - description: Category ID
        in: query
        name: category_id
        type: integer
      - description: Author ID
        in: query
        name: author_id
        type: integer
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      - description: ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetArticlesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取文章
      tags:
      - Manager
    post:
      parameters:
      - description: 文章详情
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/v1.AddArticleForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 添加文章
      tags:
      - Manager
  /manager/articles/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 删除文章
      tags:
      - Manager
    put:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category ID
        in: formData
        name: category_id
        type: integer
      - description: Page Title
        in: formData
        name: page_title
        type: string
      - description: SEO Title
        in: formData
        name: seo_title
        type: string
      - description: SEO URL
        in: formData
        name: seo_url
        type: string
      - description: Related Articles
        in: formData
        name: related_articles
        type: string
      - description: Desc
        in: formData
        name: meta_desc
        type: string
      - description: Author ID
        in: formData
        name: author_id
        type: integer
      - description: Content
        in: formData
        name: content
        type: string
      - description: Cover img URL
        in: formData
        name: cover_image_url
        type: string
      - default: 1
        description: State
        in: formData
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 修改文章
      tags:
      - Manager
  /manager/author:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetAuthorsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取作者
      tags:
      - Manager
    post:
      parameters:
      - description: 作者详情
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/v1.AddAuthorForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 添加作者
      tags:
      - Manager
  /manager/author/{id}:
    put:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Name
        in: formData
        name: name
        type: string
      - description: Age
        in: formData
        name: age
        type: integer
      - default: 2
        description: Gender
        enum:
        - 1
        - 2
        in: formData
        name: gender
        type: integer
      - description: Desc
        in: formData
        name: desc
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 编辑作者
      tags:
      - Manager
  /manager/category:
    get:
      consumes:
      - application/json
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetCategoryResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取文章类型
      tags:
      - Manager
    post:
      parameters:
      - description: 文章类型
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/v1.AddCategoryForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 添加文章类型
      tags:
      - Manager
  /manager/category/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 删除文章类型
      tags:
      - Manager
    put:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Name
        in: formData
        name: name
        type: string
      - default: 1
        description: State
        in: formData
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 修改文章类型
      tags:
      - Manager
  /manager/s3/token:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aws.TmpTokenStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取S3上传Token
      tags:
      - Manager
  /manager/user:
    get:
      parameters:
      - description: id
        in: query
        name: id
        type: integer
      - description: name
        in: query
        name: name
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取用户
      tags:
      - Manager
    post:
      parameters:
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: passwd
        in: formData
        name: passwd
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 添加用户
      tags:
      - Manager
  /manager/user/auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名和密码
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/v1.auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取Token
      tags:
      - Manager
  /manager/user/info:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetUserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 通过登录态获取当前登录用户信息
      tags:
      - Manager
  /player/lottery:
    get:
      parameters:
      - description: 用户uid
        in: query
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetLotteryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取日签
      tags:
      - Player
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Token
    type: apiKey
swagger: "2.0"
