basePath: /api/v1
definitions:
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  manager.AddArticleForm:
    properties:
      author_id:
        type: integer
      category_id:
        type: integer
      content:
        type: string
      cover_image_url:
        type: string
      language:
        enum:
        - zh
        - en
        - jp
        type: string
      meta_desc:
        type: string
      page_title:
        type: string
      related_articles:
        type: string
      seo_title:
        type: string
      seo_url:
        type: string
      state:
        description: 0表示禁用，1表示启用
        enum:
        - 0
        - 1
        type: integer
    required:
    - author_id
    - category_id
    - content
    - cover_image_url
    - language
    - meta_desc
    - page_title
    - related_articles
    - seo_title
    - seo_url
    - state
    type: object
  manager.AddAuthorForm:
    properties:
      age:
        type: integer
      createdBy:
        type: string
      desc:
        type: string
      gender:
        default: 2
        description: 1表示男，2表示女
        enum:
        - 1
        - 2
        type: integer
      name:
        type: string
    required:
    - age
    - createdBy
    - desc
    - gender
    - name
    type: object
  manager.AddTagForm:
    properties:
      created_by:
        type: string
      name:
        type: string
      state:
        default: 1
        type: integer
    required:
    - created_by
    - name
    - state
    type: object
  manager.Article:
    properties:
      authorId:
        type: integer
      categoryID:
        type: integer
      content:
        type: string
      coverImageUrl:
        type: string
      created_on:
        type: integer
      deleted_on:
        description: 0表示未删除
        type: integer
      id:
        type: integer
      language:
        type: string
      metaDesc:
        type: string
      modified_on:
        type: integer
      modifiedBy:
        type: string
      pageTitle:
        type: string
      relatedArticles:
        type: string
      seoTitle:
        type: string
      seoUrl:
        type: string
      state:
        type: integer
    type: object
  manager.Author:
    properties:
      age:
        type: integer
      created_by:
        type: string
      created_on:
        type: integer
      deleted_on:
        description: 0表示未删除
        type: integer
      desc:
        description: 简介
        type: string
      gender:
        type: integer
      id:
        type: integer
      modified_by:
        type: string
      modified_on:
        type: integer
      name:
        type: string
    type: object
  manager.GetArticlesResponse:
    properties:
      count:
        type: integer
      lists:
        items:
          $ref: '#/definitions/manager.Article'
        type: array
    type: object
  manager.GetAuthorsResponse:
    properties:
      count:
        type: integer
      lists:
        items:
          $ref: '#/definitions/manager.Author'
        type: array
    type: object
  manager.GetTagsResponse:
    properties:
      count:
        type: integer
      lists:
        items:
          $ref: '#/definitions/manager.Tag'
        type: array
    type: object
  manager.Tag:
    properties:
      created_by:
        type: string
      created_on:
        type: integer
      deleted_on:
        description: 0表示未删除
        type: integer
      id:
        type: integer
      modified_by:
        type: string
      modified_on:
        type: integer
      name:
        type: string
      state:
        description: 0表示禁用，1表示启用
        type: integer
    type: object
  manager.auth:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact:
    email: cwater4t@gmail.com
    name: cw4t
  description: 小宇宙项目用户交互API、管理后台API
  title: 小小の宇宙API文档
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名和密码
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/manager.auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取Token
      tags:
      - Manager
  /manager/articles:
    get:
      parameters:
      - description: Category ID
        in: query
        name: category_id
        type: integer
      - description: Author ID
        in: query
        name: author_id
        type: integer
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      - description: ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/manager.GetArticlesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取文章
      tags:
      - Manager
    post:
      parameters:
      - description: 文章详情
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/manager.AddArticleForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 添加文章
      tags:
      - Manager
  /manager/articles/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 删除文章
      tags:
      - Manager
    put:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category ID
        in: formData
        name: category_id
        type: integer
      - description: Page Title
        in: formData
        name: page_title
        type: string
      - description: SEO Title
        in: formData
        name: seo_title
        type: string
      - description: Desc
        in: formData
        name: meta_desc
        type: string
      - description: Author ID
        in: formData
        name: author_id
        type: integer
      - description: Content
        in: formData
        name: content
        type: string
      - description: Cover img URL
        in: formData
        name: cover_image_url
        type: string
      - description: ModifiedBy
        in: formData
        name: modified_by
        required: true
        type: string
      - description: State
        in: formData
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 修改文章
      tags:
      - Manager
  /manager/author:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/manager.GetAuthorsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取作者
      tags:
      - Manager
    post:
      parameters:
      - description: 作者详情
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/manager.AddAuthorForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 添加作者
      tags:
      - Manager
  /manager/author/{id}:
    put:
      parameters:
      - description: Name
        in: formData
        name: name
        type: string
      - description: Age
        in: formData
        name: age
        type: integer
      - default: 2
        description: Gender
        enum:
        - 1
        - 2
        in: formData
        name: gender
        type: integer
      - description: ModifiedBy
        in: formData
        name: modified_by
        required: true
        type: string
      - description: Desc
        in: formData
        name: desc
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 编辑作者
      tags:
      - Manager
  /manager/tags:
    get:
      consumes:
      - application/json
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/manager.GetTagsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取文章类型
      tags:
      - Manager
    post:
      parameters:
      - description: 文章类型
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/manager.AddTagForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 添加文章类型
      tags:
      - Manager
  /manager/tags/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 删除文章类型
      tags:
      - Manager
    put:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - default: 1
        description: State
        in: formData
        name: state
        type: integer
      - description: ModifiedBy
        in: formData
        name: modified_by
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: 修改文章类型
      tags:
      - Manager
  /player/article:
    get:
      parameters:
      - description: 用户id
        in: query
        name: uid
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: '"为玩家展示文章"'
      tags:
      - Player
  /player/tarot:
    get:
      parameters:
      - description: 用户id
        in: query
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 免费获取塔罗牌
      tags:
      - Player
  /player/tarot/read:
    post:
      parameters:
      - description: 用户id
        in: body
        name: uid
        required: true
        schema:
          type: integer
      - description: 塔罗牌id
        in: body
        name: tarotId
        required: true
        schema:
          type: string
      - description: 付费id
        in: body
        name: paidOrderId
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取塔罗牌付费内容
      tags:
      - Player
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Token
    type: apiKey
swagger: "2.0"
